# EDIT THIS FILE

title: Sample BHW #Site Title
description: Jekyll site for BHW members #Site Description
baseurl: ''
url: https://olaglam2.github.io #Site domain. Enter protocol too. http:// or https://
twitter: johndoe #Twiiter username
facebook: johndoe #FB username
instagram: johndoe #IG username
youtube: UCas0984madnjd8 #Youtube channel ID

markdown: kramdown
permalink: "/:title"
paginate: 8

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
 
  
exclude:
  - Gemfile

tag_page_layout: tag_page
tag_page_dir: tag

tag_permalink_style: pretty

# image_optim-jekyll-plugin customizations.
image_optim:
  archive_dir: "assets/full-res-kittens"
  cache_file: "tmp/kitty-cache.yml"
  image_glob: "assets/img/**/cat-*.{gif,png,jpg,jpeg}"
